---
- name: Remove Schediled Cron Job
  hosts: webservers
  become: true

  tasks:

    - name: Cron Job Removed
      ansible.builtin.cron:
        name: Add date and time to a file
        user: devops
        cron_file: add-date-time
        state: absent
